### ISSUE TITLE
Create Traceability Matrix Mapping of Use Cases

### ISSUE THREAD

**Issue by MetzgerH** [KylerKupp/python-desktop-app#8]
Use the below template (taken from Canvas assignment "Requirements and Specifications section") to write and document use cases for the product. This does not include Test Cases.

https://wsu.instructure.com/courses/1737237/files/123747444?wrap=1

**Comment by MetzgerH** [comment]
Is this necessary for Sprint 1?

**Comment by KylerKupp** [comment]
I can't seem to find any mention of it in the sprint 1 templates or rubric.
I don't remember him specifying if it was for sprint 1 in class, so I'm not
too sure
